CREATE TABLE ITEM_QUANTITY(
  ITEM_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(35) NOT NULL,
  PRICE INTEGER NOT NULL,
  QUANTITY INTEGER,
  TYPE VARCHAR(15)
);
CREATE TABLE BILL(
  BILL_ID BIGSERIAL PRIMARY KEY,
  STORE_USER_ID INTEGER NOT NULL,
  ITEM_QUANTITY_ID INTEGER  NOT NULL,
  CREATED_DATE VARCHAR(64),
  TOTAL_PRICE INTEGER,
  DISCOUNT_AMOUNT INTEGER,
  BILL_AMOUNT INTEGER
);

CREATE TABLE STORE_USER(
  STORE_USER_ID BIGSERIAL PRIMARY KEY,
  STORE_USER_TYPE VARCHAR(15) NOT NULL,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  PHONE_NUMBER VARCHAR(24)
);

ALTER TABLE BILL ADD FOREIGN KEY (STORE_USER_ID) REFERENCES STORE_USER(STORE_USER_ID);
ALTER TABLE BILL ADD FOREIGN KEY (ITEM_QUANTITY_ID) REFERENCES ITEM_QUANTITY(ITEM_ID);
