CREATE TABLE ROLES(
  ROLE_ID BIGSERIAL PRIMARY KEY,
  ROLE_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE STORE_USER(
  USER_ID BIGSERIAL PRIMARY KEY,
  ROLE VARCHAR(15) NOT NULL,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  USERNAME VARCHAR(64),
  PASSWORD VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  PHONE_NUMBER VARCHAR(24),
  JOINING_DATE TIMESTAMP
);


CREATE TABLE USER_ROLES(
  	USER_ID BIGSERIAL NOT NULL,
  	ROLE_ID BIGSERIAL NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES STORE_USER(USER_ID),
	FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID),
	PRIMARY KEY(USER_ID, ROLE_ID)
);

----------------------------------------------------

CREATE TABLE ITEM_QUANTITY(
  ITEM_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(35) NOT NULL,
  PRICE INTEGER NOT NULL,
  QUANTITY INTEGER,
  TYPE VARCHAR(15)
);
CREATE TABLE BILL(
  BILL_ID BIGSERIAL PRIMARY KEY,
  USER_ID INTEGER NOT NULL,
  ITEM_QUANTITY_ID INTEGER  NOT NULL,
  CREATED_DATE VARCHAR(64),
  TOTAL_PRICE INTEGER,
  DISCOUNT_AMOUNT INTEGER,
  BILL_AMOUNT INTEGER
);

ALTER TABLE BILL ADD FOREIGN KEY (USER_ID) REFERENCES STORE_USER(USER_ID);
ALTER TABLE BILL ADD FOREIGN KEY (ITEM_QUANTITY_ID) REFERENCES ITEM_QUANTITY(ITEM_ID);
